# Generated by Django 5.0 on 2023-12-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'LoaiNhanVien',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNV', models.TextField(blank=True)),
                ('tenNV', models.TextField(blank=True)),
                ('luongCD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luongHT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loaiNhanVien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien', to='qlnv.loainhanvien')),
            ],
            options={
                'verbose_name_plural': 'NhanVien',
            },
        ),
    ]
