# Generated by Django 5.0 on 2023-12-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlnv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='luongHT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
